[package]
name = "network_developer_console"
version = "0.1.0"
edition = "2021"

[features]
dev = ["ui_dev"]
ui_dev = []

[dependencies]
pnet = "0.28.0"
ipnetwork = "0.18.0"
serde = { version = "1", features = ["derive"] }
tui = "0.17.0"
crossterm = "0.22.1"
httparse = "1.6.0"